version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
    docker:
      - image: cimg/aws:2022.06.1
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

configure_infrastructure: 
  docker:
    - image: python:3.7-alpine3.11
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["8d:15:a5:85:85:ae:f5:35:17:d7:61:09:61:4e:ea:af"] 
    - run:
        name: Install Ansible
        command: |
          # Install Ansible
          apk add --update ansible
    - run:
        name: Run Playbook and Configure server
        command: |
          # Your command
          ansible-playbook -i inventory.txt main-remote.yml
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure
